[project]
name = "ai-window-prompts-updater"
version = "0.1.0"
description = "A script to update remote settings ai window prompts via cronjob"
authors = [
    {name = "Bryan Johns", email = "bjohns@mozilla.com"},
]
license = {text = "MPLv2"}
requires-python = "<4.0,>=3.12"
dependencies = [
    "kinto-http<12.0.0,>=11.8.0",
    "pytest>=9.0.3,<10.0.0",
    "sentry-sdk>=2.58.0,<3.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.11,<1.0.0",
]

[project.scripts]
ai-window-prompts-updater = "ai_window_prompts_updater:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 99
extend-exclude = [
    "__pycache__",
    ".venv/",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E", "W",
    # flake8
    "F",
    # isort
    "I",
]
ignore = [
    # `format` will wrap lines.
    "E501",
]

[tool.ruff.lint.isort]
lines-after-imports = 2
